Preprocessing of Data 

Required Packages

In [2]:
import pandas as pd
import numpy as np


In [35]:
data=pd.read_csv("Weight-height.csv")
data

Gender     Height      Weight
0     Male  73.847017  241.893563
1     Male  68.781904  162.310473
2     Male  74.110105  212.740856
3     Male  71.730978  220.042470
4     Male  69.881796  206.349801
5     Male  67.253016  152.212156
6     Male  68.785081         NaN
7     Male  68.348516  167.971111
8     Male  67.018950  175.929440
9   Female  65.755948  137.471104
10  Female        NaN  154.904986
11  Female  64.237742  147.205490
12  Female  63.104984  133.148254
13  Female  62.780302  145.794374
14  Female  63.473139         NaN
15  Female  66.749167  166.880316
16  Female  66.529493  149.739208
17  Female        NaN  135.387154
18  Female  64.254760  143.363850

Understanding data is required

In [4]:
data.describe()

Height      Weight
count  17.000000   17.000000
mean   67.449582  167.843800
std     3.494144   32.819682
min    62.780302  133.148254
25%    64.254760  145.794374
50%    67.018950  154.904986
75%    68.785081  175.929440
max    74.110105  241.893563

Dtypes returns datatype used in columns

In [5]:
data.dtypes

Gender     object
Height    float64
Weight    float64
dtype: object

Returns Boolean value [True -> if null , False -> if not null]

In [6]:
data.isnull()

Gender  Height  Weight
0    False   False   False
1    False   False   False
2    False   False   False
3    False   False   False
4    False   False   False
5    False   False   False
6    False   False    True
7    False   False   False
8    False   False   False
9    False   False   False
10   False    True   False
11   False   False   False
12   False   False   False
13   False   False   False
14   False   False    True
15   False   False   False
16   False   False   False
17   False    True   False
18   False   False   False

To Find how many cells or data is empty or null 

In [28]:
data.isnull().sum()

Gender    0
Height    2
Weight    2
dtype: int64

Spiltting values

In [46]:
x=data.iloc[:,1:3].values
y=data.iloc[:,-3].values


In [48]:
print(y)

['Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female'
 'Female']


Replace Null values

In [31]:
from sklearn.impute import SimpleImputer

In [39]:
impute = SimpleImputer(missing_values=np.nan,strategy='mean')
impute = impute.fit(x[:,0:3])
x[:,0:3]=impute.transform(x[:,0:3])
x

array([[ 73.84701702, 241.8935632 ],
       [ 68.78190405, 162.3104725 ],
       [ 74.11010539, 212.7408556 ],
       [ 71.7309784 , 220.0424703 ],
       [ 69.88179586, 206.3498006 ],
       [ 67.25301569, 152.2121558 ],
       [ 68.78508125, 167.84380029],
       [ 68.34851551, 167.9711105 ],
       [ 67.01894966, 175.9294404 ],
       [ 65.75594816, 137.4711041 ],
       [ 67.44958222, 154.9049863 ],
       [ 64.23774197, 147.2054901 ],
       [ 63.10498437, 133.1482542 ],
       [ 62.78030163, 145.7943741 ],
       [ 63.4731386 , 167.84380029],
       [ 66.74916684, 166.8803156 ],
       [ 66.52949335, 149.7392078 ],
       [ 67.44958222, 135.3871538 ],
       [ 64.25475995, 143.3638501 ]])

Change String values to Numerical Form

In [42]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(y)


In [43]:
print(y)

[1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]


Test train set split 

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [44]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [45]:
print(x_train)

[[ 2.05698829  1.53984877]
 [-1.07398093  0.08285274]
 [ 0.81239411  1.33244671]
 [-0.17434921 -0.5046762 ]
 [ 0.36107621  0.0869842 ]
 [ 0.48864323 -0.09671442]
 [-1.27791606 -0.63269366]
 [ 1.97954878  2.48591035]
 [-0.84391229 -0.71156885]
 [ 0.09647705 -0.97042803]
 [-0.40204064 -0.90279982]
 [-0.03027876  0.34524735]
 [-1.18234636 -1.04308464]
 [-0.8489215  -0.58690023]
 [ 0.03861809 -0.42442427]]


In [16]:
print(x_test)

[[ 1.35669718  1.77680024]
 [-0.10968877  0.0515858 ]
 [ 0.48957843  0.08285274]
 [ 0.09647705 -0.33703673]]


In [17]:
print(y_train)

[1 0 1 0 1 1 0 1 0 0 0 1 0 0 1]


In [18]:
print(y_test)

[1 0 1 0]
